Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Cloud-init v. 19.3-44.amzn2 running 'init-local' at Tue, 21 Sep 2021 16:05:55 +0000. Up 6.42 seconds.
Sep 21 16:05:56 cloud-init[1700]: main.py[DEBUG]: No kernel command line url found.
Sep 21 16:05:56 cloud-init[1700]: main.py[DEBUG]: Closing stdin.
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Sep 21 16:05:56 cloud-init[1700]: handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Sep 21 16:05:56 cloud-init[1700]: stages.py[DEBUG]: no cache found
Sep 21 16:05:56 cloud-init[1700]: handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Sep 21 16:05:56 cloud-init[1700]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 21 16:05:56 cloud-init[1700]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Sep 21 16:05:56 cloud-init[1700]: __init__.py[DEBUG]: Searching for local data source in: []
Sep 21 16:05:56 cloud-init[1700]: main.py[DEBUG]: No local datasource found
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Sep 21 16:05:56 cloud-init[1700]: stages.py[DEBUG]: network config disabled by system_cfg
Sep 21 16:05:56 cloud-init[1700]: stages.py[INFO]: network config is disabled by system_cfg
Sep 21 16:05:56 cloud-init[1700]: main.py[DEBUG]: [local] Exiting without datasource
Sep 21 16:05:56 cloud-init[1700]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpLJDX08) - w: [644] 488 bytes/chars
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Sep 21 16:05:56 cloud-init[1700]: util.py[DEBUG]: cloud-init mode 'init' took 0.056 seconds (0.05)
Sep 21 16:05:56 cloud-init[1700]: handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Cloud-init v. 19.3-44.amzn2 running 'init' at Tue, 21 Sep 2021 16:05:56 +0000. Up 7.40 seconds.
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: No kernel command line url found.
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: Closing stdin.
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: no cache found
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Searching for network data source in: [u'DataSourceEc2', u'DataSourceNone']
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1294 bytes from /proc/self/status
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_uuid (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_uuid
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_uuid returned EC237825-49A5-B67D-44D5-EA686AED8D03
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1294 bytes from /proc/self/status
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec237825-49a5-b67d-44d5-ea686aed8d03
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1294 bytes from /proc/self/status
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/chassis_asset_tag
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned Amazon EC2
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1294 bytes from /proc/self/status
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/sys_vendor
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Amazon EC2
Sep 21 16:05:57 cloud-init[2019]: DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.003 seconds
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.001 seconds
Sep 21 16:05:57 cloud-init[2019]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Sep 21 16:05:57 cloud-init[2019]: DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/api/token' with {'url': 'http://169.254.169.254/latest/api/token', 'headers': {'X-aws-ec2-metadata-token-ttl-seconds': '21600', 'User-Agent': 'Cloud-Init/19.3-44.amzn2'}, 'allow_redirects': True, 'method': 'PUT', 'timeout': 1.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/api/token (200, 56b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ==', 'User-Agent': 'Cloud-Init/19.3-44.amzn2'}, 'allow_redirects': True, 'method': 'GET'} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'url': 'http://169.254.169.254/2016-09-02/user-data', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/user-data (200, 613b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 263b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ (200, 230b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ipv4-associations/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ipv4-associations/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ipv4-associations/ (200, 14b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ipv4-associations/34.217.102.155' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ipv4-associations/34.217.102.155', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/ipv4-associations/34.217.102.155 (200, 12b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/local-hostname (200, 42b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/security-groups (200, 7b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/public-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/public-hostname (200, 50b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-ipv4-cidr-blocks', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/subnet-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/subnet-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/subnet-id (200, 15b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/public-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/public-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/public-ipv4s (200, 14b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/interface-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/interface-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/interface-id (200, 21b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/mac (200, 17b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/security-group-ids' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/security-group-ids', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/security-group-ids (200, 11b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/local-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/local-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/local-ipv4s (200, 12b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/owner-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/owner-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/owner-id (200, 12b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/subnet-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/device-number' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/device-number', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/device-number (200, 1b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/02:ab:b6:2f:a5:51/vpc-id (200, 12b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 5b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 729b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 12b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 42b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 7b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 50b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 42b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 14b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 8b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 32b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 476b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAK0lF3NYYO9jdqWeurHj0Rg8UpprPl_bNLVl1fWfTBF1V3qrHQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Sep 21 16:05:57 cloud-init[2019]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1499b) after 1 attempts
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Crawl of metadata service took 0.147 seconds
Sep 21 16:05:57 cloud-init[2019]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpGNptC6) - w: [644] 7931 bytes/chars
Sep 21 16:05:57 cloud-init[2019]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp4NU7b1) - w: [600] 7931 bytes/chars
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
Sep 21 16:05:57 cloud-init[2019]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1610 bytes from /etc/cloud/cloud.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 1610 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 29 bytes from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 29 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: loaded blob returned None, returning default.
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-00b8b90717dff9761'
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-00b8b90717dff9761/datasource (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/datasource - wb: [644] 29 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12957 bytes
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: [net] init will now be targeting instance id: i-00b8b90717dff9761. new=True
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1610 bytes from /etc/cloud/cloud.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 1610 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 29 bytes from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 29 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: loaded blob returned None, returning default.
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: network config disabled by system_cfg
Sep 21 16:05:57 cloud-init[2019]: stages.py[INFO]: network config is disabled by system_cfg
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/user-data.txt - wb: [600] 613 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/user-data.txt.i - wb: [600] 956 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/vendor-data.txt - wb: [600] 0 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/vendor-data.txt.i - wb: [600] 345 bytes
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 21 16:05:57 cloud-init[2019]: cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-25-80.us-west-2.compute.internal (ip-172-31-25-80)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-25-80.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-25-80.us-west-2.compute.internal
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['hostname', 'ip-172-31-25-80.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpHULVKR) - w: [644] 91 bytes/chars
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/consume_data - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/consume_data'>)
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
Sep 21 16:05:57 cloud-init[2019]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Added default handler for set(['text/jinja2']) from JinjaTemplatePartHandler: [['text/jinja2']]
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, part-001, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/part-001 - wb: [700] 613 bytes
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/cloud-config.txt - wb: [600] 0 bytes
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: no vendordata from datasource
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1610 bytes from /etc/cloud/cloud.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 1610 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 29 bytes from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 29 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: loaded blob returned None, returning default.
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: loaded blob returned None, returning default.
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: loaded blob returned None, returning default.
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 14873 bytes
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: no di_report found in config.
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f2e0d92ed90>)
Sep 21 16:05:57 cloud-init[2019]: cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f2e0d92eb50>)
Sep 21 16:05:57 cloud-init[2019]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_write_files - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_write_files'>)
Sep 21 16:05:57 cloud-init[2019]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_write_metadata - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_write_metadata'>)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module amazonlinux_repo_https (<module 'cloudinit.config.cc_amazonlinux_repo_https' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_amazonlinux_repo_https.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-amazonlinux_repo_https: running config-amazonlinux_repo_https with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_amazonlinux_repo_https - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-amazonlinux_repo_https using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_amazonlinux_repo_https'>)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['amazon-linux-https', 'enable'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-amazonlinux_repo_https: SUCCESS: config-amazonlinux_repo_https ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f2e0c371210>)
Sep 21 16:05:57 cloud-init[2019]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/2019/mountinfo (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2536 bytes from /proc/2019/mountinfo
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1295 bytes from /proc/self/status
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: resize_devices took 0.068 seconds
Sep 21 16:05:57 cloud-init[2019]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f2e0d941910>)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/2019/mountinfo (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 2536 bytes from /proc/2019/mountinfo
Sep 21 16:05:57 cloud-init[2019]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 1295 bytes from /proc/self/status
Sep 21 16:05:57 cloud-init[2019]: cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Forked child 2164 who will run callback log_time
Sep 21 16:05:57 cloud-init[2019]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
Sep 21 16:05:57 cloud-init[2164]: util.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-set-hostname: running config-set-hostname with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_set_hostname - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_set_hostname'>)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 91 bytes from /var/lib/cloud/data/set-hostname
Sep 21 16:05:57 cloud-init[2019]: cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-set-hostname: SUCCESS: config-set-hostname ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-update-hostname: running config-update-hostname with frequency always
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f2e0c276d50>)
Sep 21 16:05:57 cloud-init[2019]: cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-25-80.us-west-2.compute.internal (ip-172-31-25-80)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-25-80.us-west-2.compute.internal in 1 files
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 42 bytes
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-update-hostname: SUCCESS: config-update-hostname ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-update-etc-hosts: running config-update-etc-hosts with frequency always
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f2e0c276c90>)
Sep 21 16:05:57 cloud-init[2019]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-update-etc-hosts: SUCCESS: config-update-etc-hosts ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_rsyslog - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_rsyslog'>)
Sep 21 16:05:57 cloud-init[2019]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_users_groups - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_users_groups'>)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
Sep 21 16:05:57 cloud-init[2019]: __init__.py[DEBUG]: Adding user ec2-user
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ec2-user', '--comment', 'EC2 Default User', '--groups', 'adm,systemd-journal,wheel', '--shell', '/bin/bash', '-m']
Sep 21 16:05:57 cloud-init[2164]: util.py[DEBUG]: backgrounded Resizing took 0.034 seconds
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 4328 bytes from /etc/sudoers
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 135 bytes
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_ssh - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_ssh'>)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 3958 bytes from /etc/ssh/sshd_config
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 729 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 3958 bytes from /etc/ssh/sshd_config
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 886 bytes
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
Sep 21 16:05:57 cloud-init[2019]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: start: init-network/config-resolv-conf: running config-resolv-conf with frequency once-per-instance
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_resolv_conf - wb: [644] 20 bytes
Sep 21 16:05:57 cloud-init[2019]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_resolv_conf'>)
Sep 21 16:05:57 cloud-init[2019]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network/config-resolv-conf: SUCCESS: config-resolv-conf ran successfully
Sep 21 16:05:57 cloud-init[2019]: main.py[DEBUG]: Ran 14 modules with 0 failures
Sep 21 16:05:57 cloud-init[2019]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpH6PrZC) - w: [644] 525 bytes/chars
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Sep 21 16:05:57 cloud-init[2019]: util.py[DEBUG]: cloud-init mode 'init' took 0.822 seconds (0.83)
Sep 21 16:05:57 cloud-init[2019]: handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Cloud-init v. 19.3-44.amzn2 running 'modules:config' at Tue, 21 Sep 2021 16:05:58 +0000. Up 8.84 seconds.
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disk_setup.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-disk_setup: running config-disk_setup with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_disk_setup - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_disk_setup'>)
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-disk_setup: SUCCESS: config-disk_setup ran successfully
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-mounts: running config-mounts with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_mounts - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_mounts'>)
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: mounts configuration is [['ephemeral0', '/media/ephemeral0'], ['swap', 'none', 'swap', 'sw', '0', '0']]
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Read 91 bytes from /etc/fstab
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Sep 21 16:05:58 cloud-init[2203]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Sep 21 16:05:58 cloud-init[2203]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: changed swap => None
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Sep 21 16:05:58 cloud-init[2203]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Sep 21 16:05:58 cloud-init[2203]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: changed default device swap => None
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: no need to setup swap
Sep 21 16:05:58 cloud-init[2203]: cc_mounts.py[DEBUG]: No modifications to fstab needed
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-mounts: SUCCESS: config-mounts ran successfully
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_locale - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_locale'>)
Sep 21 16:05:58 cloud-init[2203]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 93 bytes
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_set_passwords - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_set_passwords'>)
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Read 3958 bytes from /etc/ssh/sshd_config
Sep 21 16:05:58 cloud-init[2203]: ssh_util.py[DEBUG]: line 63: option PasswordAuthentication updated yes -> no
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [600] 3957 bytes
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Running command ['service', 'sshd', 'restart'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:05:58 cloud-init[2203]: cc_set_passwords.py[DEBUG]: Restarted the ssh daemon.
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-yum-configure: running config-yum-configure with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_yum_configure - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_yum_configure'>)
Sep 21 16:05:58 cloud-init[2203]: cc_yum_configure.py[DEBUG]: Generating default repo files
Sep 21 16:05:58 cloud-init[2203]: __init__.py[DEBUG]: filtered distro mirror info: {}
Sep 21 16:05:58 cloud-init[2203]: cc_yum_configure.py[DEBUG]: mirror_info: {}
Sep 21 16:05:58 cloud-init[2203]: cc_yum_configure.py[DEBUG]: No mirror info found; ignoring.
Sep 21 16:05:58 cloud-init[2203]: cc_yum_configure.py[INFO]: No releasever provided, leaving yum.conf unchanged.
Sep 21 16:05:58 cloud-init[2203]: cc_yum_configure.py[INFO]: No repo target provided, leaving target unchanged.
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-yum-configure: SUCCESS: config-yum-configure ran successfully
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_yum_add_repo - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_yum_add_repo'>)
Sep 21 16:05:58 cloud-init[2203]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
Sep 21 16:05:58 cloud-init[2203]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Sep 21 16:05:58 cloud-init[2203]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_package_update_upgrade_install'>)
Sep 21 16:05:58 cloud-init[2203]: amazon.py[DEBUG]: Upgrade level: security
Sep 21 16:05:58 cloud-init[2203]: rhel.py[DEBUG]: Using YUM for package management
Sep 21 16:05:58 cloud-init[2203]: util.py[DEBUG]: Running command ['yum', '-t', '-y', '--exclude=kernel', '--exclude=nvidia*', '--exclude=cuda*', '--security', '--sec-severity=critical', '--sec-severity=important', 'upgrade'] with allowed return codes [0] (shell=False, capture=False)
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
Sep 21 16:06:06 cloud-init[2203]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
Sep 21 16:06:06 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_timezone - wb: [644] 20 bytes
Sep 21 16:06:06 cloud-init[2203]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_timezone'>)
Sep 21 16:06:06 cloud-init[2203]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
Sep 21 16:06:06 cloud-init[2203]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
Sep 21 16:06:06 cloud-init[2203]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f418584b710>)
Sep 21 16:06:06 cloud-init[2203]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
Sep 21 16:06:06 cloud-init[2203]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
Sep 21 16:06:06 cloud-init[2203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_runcmd - wb: [644] 20 bytes
Sep 21 16:06:06 cloud-init[2203]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_runcmd'>)
Sep 21 16:06:06 cloud-init[2203]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
Sep 21 16:06:06 cloud-init[2203]: main.py[DEBUG]: Ran 10 modules with 0 failures
Sep 21 16:06:06 cloud-init[2203]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpWS3I2n) - w: [644] 551 bytes/chars
Sep 21 16:06:06 cloud-init[2203]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 21 16:06:06 cloud-init[2203]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Sep 21 16:06:06 cloud-init[2203]: util.py[DEBUG]: cloud-init mode 'modules' took 8.114 seconds (7.00)
Sep 21 16:06:06 cloud-init[2203]: handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
Sep 21 16:06:07 cloud-init[2377]: util.py[DEBUG]: Cloud-init v. 19.3-44.amzn2 running 'modules:final' at Tue, 21 Sep 2021 16:06:07 +0000. Up 16.46 seconds.
Sep 21 16:06:07 cloud-init[2377]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Sep 21 16:06:07 cloud-init[2377]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
Sep 21 16:06:07 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 20 bytes
Sep 21 16:06:07 cloud-init[2377]: helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
Sep 21 16:06:07 cloud-init[2377]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
Sep 21 16:06:07 cloud-init[2377]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f98fdbe4c90>)
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
Sep 21 16:06:07 cloud-init[2377]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
Sep 21 16:06:07 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_scripts_per_instance - wb: [644] 20 bytes
Sep 21 16:06:07 cloud-init[2377]: helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_scripts_per_instance'>)
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
Sep 21 16:06:07 cloud-init[2377]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
Sep 21 16:06:07 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
Sep 21 16:06:07 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_scripts_user - wb: [644] 20 bytes
Sep 21 16:06:07 cloud-init[2377]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_scripts_user'>)
Sep 21 16:06:07 cloud-init[2377]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
Sep 21 16:06:23 cloud-init[2377]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_ssh_authkey_fingerprints - wb: [644] 20 bytes
Sep 21 16:06:23 cloud-init[2377]: helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_ssh_authkey_fingerprints'>)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Read 3957 bytes from /etc/ssh/sshd_config
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Read 729 bytes from /home/ec2-user/.ssh/authorized_keys
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
Sep 21 16:06:23 cloud-init[2377]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_keys_to_console - wb: [644] 20 bytes
Sep 21 16:06:23 cloud-init[2377]: helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_keys_to_console'>)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
Sep 21 16:06:23 cloud-init[2377]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_phone_home - wb: [644] 20 bytes
Sep 21 16:06:23 cloud-init[2377]: helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_phone_home'>)
Sep 21 16:06:23 cloud-init[2377]: cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
Sep 21 16:06:23 cloud-init[2377]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
Sep 21 16:06:23 cloud-init[2377]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f98fdb46a10>)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Cloud-init v. 19.3-44.amzn2 finished at Tue, 21 Sep 2021 16:06:23 +0000. Datasource DataSourceEc2.  Up 32.42 seconds
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 59 bytes
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
Sep 21 16:06:23 cloud-init[2377]: stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_power_state_change.pyc'>) with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_power_state_change - wb: [644] 20 bytes
Sep 21 16:06:23 cloud-init[2377]: helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-00b8b90717dff9761/sem/config_power_state_change'>)
Sep 21 16:06:23 cloud-init[2377]: cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
Sep 21 16:06:23 cloud-init[2377]: main.py[DEBUG]: Ran 9 modules with 0 failures
Sep 21 16:06:23 cloud-init[2377]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp1x7cao) - w: [644] 576 bytes/chars
Sep 21 16:06:23 cloud-init[2377]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpWUsyKp) - w: [644] 65 bytes/chars
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Sep 21 16:06:23 cloud-init[2377]: util.py[DEBUG]: cloud-init mode 'modules' took 15.967 seconds (15.97)
Sep 21 16:06:23 cloud-init[2377]: handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
